"""Markdown report generation."""

from __future__ import annotations

from grok_inspect.models import ScanResult


def to_markdown(result: ScanResult) -> str:
    lines: list[str] = []
    lines.append("# Grok Inspect Report")
    lines.append("")
    lines.append(f"- **Tool version:** {result.tool_version}")
    lines.append(f"- **Started:** {result.started_at.isoformat()}")
    lines.append(f"- **Finished:** {result.finished_at.isoformat()}")
    lines.append(f"- **Elevated:** {result.elevated}")
    lines.append(
        f"- **Host:** {result.host.get('hostname')} "
        f"({result.host.get('os_family')} {result.host.get('release')})"
    )
    lines.append(
        f"- **Max severity:** {result.score.max_severity.value} "
        f"({result.score.open_finding_count} open findings)"
    )
    lines.append("")
    lines.append("## Score")
    lines.append("")
    for sev, count in result.score.counts.items():
        lines.append(f"- {sev}: {count}")
    lines.append("")
    lines.append("## Coverage")
    lines.append("")
    for c in result.coverage:
        detail = f" — {c.detail}" if c.detail else ""
        lines.append(f"- `{c.collector}`: **{c.status.value}**{detail}")
    lines.append("")
    lines.append("## Findings")
    lines.append("")
    open_f = [f for f in result.findings if not f.acknowledged]
    if not open_f:
        lines.append("_No open findings._")
    for f in open_f:
        lines.append(f"### [{f.severity.value.upper()}] {f.title}")
        lines.append("")
        lines.append(f"- **ID:** `{f.id}`")
        lines.append(f"- **Category:** {f.category}")
        lines.append(f"- **Confidence:** {f.confidence}")
        lines.append(f"- **Summary:** {f.summary}")
        if f.remediation_hint:
            lines.append(f"- **Hint:** {f.remediation_hint}")
        lines.append("")
    ack = [f for f in result.findings if f.acknowledged]
    if ack:
        lines.append("## Acknowledged (allowlisted)")
        lines.append("")
        for f in ack:
            lines.append(f"- `{f.id}` — {f.title}")
        lines.append("")
    lines.append("## Grok Analysis")
    lines.append("")
    g = result.grok
    if g.available:
        lines.append(f"- **Model:** {g.model_id} (reasoning_effort={g.reasoning_effort})")
        if g.latency_s is not None:
            lines.append(f"- **Latency:** {g.latency_s:.1f}s")
        if g.usage_summary:
            lines.append(f"- **Usage:** {g.usage_summary}")
        lines.append("")
        lines.append("### Executive summary")
        lines.append("")
        lines.append(g.executive_summary or "_empty_")
        lines.append("")
        lines.append("### Threat narrative")
        lines.append("")
        lines.append(g.threat_narrative or "_empty_")
        lines.append("")
        if g.remediation_plan:
            lines.append("### Remediation plan")
            lines.append("")
            for i, step in enumerate(g.remediation_plan, 1):
                lines.append(f"{i}. {step}")
            lines.append("")
        if g.likely_attacker_goals:
            lines.append("### Likely attacker goals")
            lines.append("")
            for goal in g.likely_attacker_goals:
                lines.append(f"- {goal}")
            lines.append("")
        if g.questions_for_operator:
            lines.append("### Questions for operator")
            lines.append("")
            for q in g.questions_for_operator:
                lines.append(f"- {q}")
            lines.append("")
    else:
        lines.append(
            f"_Grok analysis unavailable:_ {g.error or 'skipped / no API key'}"
        )
        lines.append("")
    lines.append("---")
    lines.append("_Generated by grok-inspect. Defensive inspection only._")
    lines.append("")
    return "\n".join(lines)
